version: "3"
services:
  postgis:
    image: pgrouting/pgrouting:v2.6.3-postgresql_10
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  db-data:
